# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="BRICKER"
MODULE_VERSION="0.901"


inherit perl-module

DESCRIPTION="Load and save configuration files in a standard format"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

DEPEND="perl-gcpan/Class-Std
	dev-lang/perl"
