# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="JMGDOC"
MODULE_VERSION="2.125"


inherit perl-module

DESCRIPTION="The Perl Open OpenDocument Connector"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

DEPEND=">=dev-perl/Archive-Zip-1.300.0
	>=dev-perl/XML-Twig-3.440.0
	dev-lang/perl"
