# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="RBO"


inherit perl-module

DESCRIPTION="Templating module that generates Excel"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

DEPEND="dev-perl/IO-stringy
	dev-perl/Test-Exception
	>=dev-perl/Spreadsheet-WriteExcel-2.370.0
	dev-perl/Test-Deep
	dev-perl/XML-Parser
	dev-lang/perl"
